name: Sample application deployment
on:
  push:
    branches: [ main ]
    tags: [ '*\.*\.*' ]

jobs:
  publish_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Chechout code
      uses: actions/checkout@v3
    - name: Read tags
      id: read
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.read.outputs.tag }}
      run: |
        echo tag: ${{ steps.read.outputs.tag }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: ${{ steps.read.outputs.tag }} != 'main'
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v3
      if: ${{ steps.read.outputs.tag }} != 'main'
      with:
        push: true
        tags: devkrolikowski/sample-app:${{ steps.read.outputs.tag }}
  deploy_on_kubernetes:
    runs-on: home-runner
    if: ${{ steps.read.outputs.tag }} != 'main'
    steps:
      - name: Chechout k8s manifests
        uses: actions/checkout@v3
        with:
          repository: HomeDevopsLab/sample-app-k8s
          ref: refs/heads/main
      - name: Deploy on k3-lab kubernetes cluster
        run: |-
          kubectl apply -f .
